apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: cluster-admin
    rules:
        - apiGroups: [""]
              resources: ["pods", "services", "nodes"]
                    verbs: ["get", "list", "watch"]

