name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1

      - name: Build and push Docker image for Vote
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -f example-voting-app-main/vote/Dockerfile -t 851725539465.dkr.ecr.us-east-1.amazonaws.com/votingapp-ecr:latest example-voting-app-main/vote --push

      - name: Build and push Docker image for Result
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -f example-voting-app-main/result/Dockerfile -t 851725539465.dkr.ecr.us-east-1.amazonaws.com/votingapp-ecr:latest example-voting-app-main/result --push

      - name: Build and push Docker image for Worker
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -f example-voting-app-main/worker/Dockerfile -t 851725539465.dkr.ecr.us-east-1.amazonaws.com/votingapp-ecr:latest example-voting-app-main/worker --push

      - name: Register ECS task definition
        run: |
          aws ecs register-task-definition --cli-input-json file://.github/workflows/ecs-task-definition.json

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster votingapp-ecscluster-demo --service example-voting-app-service --force-new-deployment
      
      - name: Install Argo CD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/download/v2.7.1/argocd-linux-amd64
          chmod +x ./argocd
          sudo mv ./argocd /usr/local/bin/argocd
      
      - name: Sync Argo CD application
        run: |
          argocd app sync example-voting-app
